[colors.bright]
black = "0x2e3436"
blue = "0x729fcf"
cyan = "0x34e2e2"
green = "0x8ae234"
magenta = "0xad7fa8"
red = "0xef2929"
white = "0xeeeeec"
yellow = "0xfce94f"

[colors.normal]
black = "0x2e3436"
blue = "0x3465a4"
cyan = "0x06989a"
green = "0x73d216"
magenta = "0x75507b"
red = "0xcc0000"
white = "0xd3d7cf"
yellow = "0xedd400"

[colors.primary]
foreground = "0xeeeeec"

[font]
size = 12

[font.bold]
family = "JetBrainsMonoNerdFontPropo"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFontPropo"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFontPropo"
style = "italic"

[font.normal]
family = "JetBrainsMonoNerdFontPropo"
style = "Medium"

[window]
dynamic_padding = true
#history = 10000
#multiplier = 3
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 3
y = 0

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "on"

[bell]
animation = "Ease"
